name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm start & wait-on http://localhost:3000

on:
  pull_request_target:
    types:
      - closed

jobs:
  build: 
    if_merged:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "pup-trainer" #Must be unique in Heroku
            heroku_email: "aominhlong@yahoo.com"

